import type { ScoredArticle, DigestMetadata } from "../types.js";
import { formatDateTime, truncate } from "../util.js";

function scoreColor(score: number): string {
  if (score >= 0.8) return "#22c55e";
  if (score >= 0.6) return "#eab308";
  if (score >= 0.4) return "#f97316";
  return "#94a3b8";
}

function scoreLabel(score: number): string {
  if (score >= 0.8) return "High";
  if (score >= 0.6) return "Medium";
  if (score >= 0.4) return "Low";
  return "—";
}

function escapeHtml(str: string): string {
  return str
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;");
}

function articleCard(article: ScoredArticle): string {
  const color = scoreColor(article.score);
  const label = scoreLabel(article.score);
  const title = escapeHtml(article.title);
  const summary = escapeHtml(article.summary || "");
  const source = escapeHtml(article.source);
  const topics = article.topics.map((t) => escapeHtml(t));
  const publishedAt = article.publishedAt ? new Date(article.publishedAt).toLocaleDateString("en-US", { month: "short", day: "numeric" }) : "";

  return `
    <article class="card">
      <div class="card-header">
        <span class="score" style="background: ${color}">${label} ${(article.score * 100).toFixed(0)}%</span>
        <span class="source">${source}</span>
        ${publishedAt ? `<span class="date">${publishedAt}</span>` : ""}
      </div>
      <h2><a href="${escapeHtml(article.url)}" target="_blank" rel="noopener">${title}</a></h2>
      ${summary ? `<p class="summary">${summary}</p>` : ""}
      ${topics.length ? `<div class="topics">${topics.map((t) => `<span class="topic">${t}</span>`).join("")}</div>` : ""}
    </article>`;
}

export function generateHtml(articles: ScoredArticle[], metadata: DigestMetadata): string {
  const generated = formatDateTime(metadata.generatedAt);
  const topicsList = metadata.topTopics.map((t) => escapeHtml(t)).join(", ");

  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Newsbot Digest — ${generated}</title>
  <style>
    :root {
      --bg: #ffffff;
      --fg: #1a1a2e;
      --card-bg: #f8f9fa;
      --card-border: #e2e8f0;
      --link: #2563eb;
      --muted: #64748b;
      --topic-bg: #e2e8f0;
    }
    @media (prefers-color-scheme: dark) {
      :root {
        --bg: #0f172a;
        --fg: #e2e8f0;
        --card-bg: #1e293b;
        --card-border: #334155;
        --link: #60a5fa;
        --muted: #94a3b8;
        --topic-bg: #334155;
      }
    }
    * { margin: 0; padding: 0; box-sizing: border-box; }
    body {
      font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif;
      background: var(--bg);
      color: var(--fg);
      line-height: 1.6;
      max-width: 720px;
      margin: 0 auto;
      padding: 2rem 1rem;
    }
    header {
      margin-bottom: 2rem;
      padding-bottom: 1rem;
      border-bottom: 1px solid var(--card-border);
    }
    header h1 { font-size: 1.5rem; margin-bottom: 0.25rem; }
    .meta { color: var(--muted); font-size: 0.875rem; }
    .card {
      background: var(--card-bg);
      border: 1px solid var(--card-border);
      border-radius: 8px;
      padding: 1.25rem;
      margin-bottom: 1rem;
    }
    .card-header {
      display: flex;
      align-items: center;
      gap: 0.75rem;
      margin-bottom: 0.5rem;
      font-size: 0.8rem;
    }
    .score {
      color: white;
      padding: 2px 8px;
      border-radius: 4px;
      font-weight: 600;
      font-size: 0.75rem;
    }
    .source { color: var(--muted); }
    .date { color: var(--muted); }
    .card h2 {
      font-size: 1.1rem;
      margin-bottom: 0.5rem;
      line-height: 1.3;
    }
    .card h2 a {
      color: var(--link);
      text-decoration: none;
    }
    .card h2 a:hover { text-decoration: underline; }
    .summary {
      color: var(--muted);
      font-size: 0.9rem;
      margin-bottom: 0.5rem;
    }
    .topics { display: flex; flex-wrap: wrap; gap: 0.375rem; }
    .topic {
      background: var(--topic-bg);
      padding: 2px 8px;
      border-radius: 4px;
      font-size: 0.75rem;
      color: var(--muted);
    }
    footer {
      margin-top: 2rem;
      padding-top: 1rem;
      border-top: 1px solid var(--card-border);
      color: var(--muted);
      font-size: 0.8rem;
      text-align: center;
    }
  </style>
</head>
<body>
  <header>
    <h1>Newsbot Digest</h1>
    <p class="meta">
      ${metadata.articleCount} articles from ${metadata.sourcesScanned} sources
      — Generated ${generated}
    </p>
    ${topicsList ? `<p class="meta">Topics: ${topicsList}</p>` : ""}
  </header>
  <main>
    ${articles.map(articleCard).join("\n")}
  </main>
  <footer>
    Generated by Newsbot
  </footer>
</body>
</html>`;
}
